//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcstok1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public int MUSTERİID { get; set; }
        public string MUSTERİAD { get; set; }
        public string MUSTERİSOYAD { get; set; }
    }
}
