//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcstok1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        public int SATISID { get; set; }
        public string URUN { get; set; }
        public Nullable<int> MUSTERİ { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<int> FİYAT { get; set; }
    }
}
