//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcstok1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public string URUNKATEGORİ { get; set; }
        public Nullable<int> FİYAT { get; set; }
        public string MARKA { get; set; }
        public Nullable<int> STOK { get; set; }
    }
}
